### PR TITLE
feet: alternative docker build

### PR DESCRIPTION
**Pull request by leath-dub**
Thought Id contribute a dockerfile as that is how I installed it in the first place.

### CODE REVIEW

**Comment by gennaro-tedesco** [comment]
Thank you very much for your contribution, this is indeed a great idea! 

Is the additional `config.json` necessary to add, can one not just refer to one of the provided examples (this is to avoid confusion for new users who see this and that other configuration and do not understand where the examples live)?

**Comment by leath-dub** [comment]
Ok my latest commits changed it so you can specify the path to you json file in the docker run command. The command is becoming unwieldy though maybe it should be put in a script on its own

**Comment by gennaro-tedesco** [comment]
>  The command is becoming unwieldy though maybe it should be put in a script on its own

what command in particular are you referring to?

**Comment by leath-dub** [comment]
> > The command is becoming unwieldy though maybe it should be put in a script on its own
> 
> what command in particular are you referring to?

If you look at my additions to README, the docker command is very long
```
docker run --rm --name zathuraconf $(docker build --build-arg config=./config.json -q .) >| ~/.config/zathura/zathurarc
```

**Comment by gennaro-tedesco** [comment]
> If you look at my additions to README, the docker command is very long

hmm, why do we need to pass the configuration in the first place though? Namely the Dockerfile (and accordingly the docker run instructions) should only install the application within the container: once in there, the user can access the container and create their own configuration without the need for it to be passed a priori.

I am however fine merging it as is. Let me know what you think about it and if so we finalise it :)

**Comment by leath-dub** [comment]
> > If you look at my additions to README, the docker command is very long
> 
> hmm, why do we need to pass the configuration in the first place though? Namely the Dockerfile (and accordingly the docker run instructions) should only install the application within the container: once in there, the user can access the container and create their own configuration without the need for it to be passed a priori.
> 
> I am however fine merging it as is. Let me know what you think about it and if so we finalise it :)

I think that that is harder to explain, I feel like most people just want a one line command to get what they were looking for. I think maybe best of both world would be to just add both the docker run instructions and the docker build ones.

Its your call :)

**Comment by gennaro-tedesco** [comment]
I have merged! If users run into confusion or troubles I will amend it accordingly, for the moment I would say fine as is.

Again thank you very much for contributing!

**Comment by leath-dub** [comment]
grand, Ill keep an eye out, thanks !

**Pull request merged**
